version: '1'

services:
  db:
    image: postgres:14beta2-alpine3.14
    restart: always
    environment:
      POSTGRES_PASSWORD: qwerty      
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports: 
      - "5432:5432"